apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
  - image: marcinwolder/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: src/**/*.ts
manifests:
  rawYaml:
  - infra/k8s/auth-depl.yaml
