apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ticketing
build:
  googleCloudBuild:
    projectId: "ticketing-374023"
  artifacts:
  - image: "gcr.io/ticketing-374023/auth"
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: src/**/*.ts
  - image: "gcr.io/ticketing-374023/client"
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: ./**/*.[ts/tsx/js/jsx]
manifests:
  rawYaml:
  - infra/k8s/*.yaml
