apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ticketing
build:
  googleCloudBuild:
    projectId: ticketing-374023
  artifacts:
  - image: us.gcr.io/ticketing-374023/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: src/**/*.ts
manifests:
  rawYaml:
  - infra/k8s/*.yaml
