apiVersion: v1
kind: Service
metadata:
  name: tickets-mysql-ip-srv
spec:
  type: ClusterIP
  selector:
    app: tickets-mysql
  ports:
    - name: db
      protocol: TCP
      port: 8080
      targetPort: 8080